WEBHOOK_PHRASE = ""

API_KEY = "TZtbfmTW86knUL7muSUAAMMITCoC8CtyqzzVrh39NoXqMJSlGUovdU2FQgRoQCW4"
API_SECRET = "BxDQs8pvI4f6HESyMz1Ruf8w7t0SXqbKhHIgVHMd5AE3NqgEwRycUE63Xc1qYRNu"

KRAKEN_API_KEY = ""
KRAKEN_API_SECRET = ""